ab = " Hello "
print(ab)
print(next(iter(ab)))
print(next(iter(ab)))
print(next(iter(ab)))
print(next(iter(ab)))
ab = iter(ab)
print(next(iter(ab)))
print(next(iter(ab)))
print(next(iter(ab)))
print(next(iter(ab)))
print(next(iter(ab)))
print(next(iter(ab)))
print(next(iter(ab)))
print(next(iter(ab)))
print(next(iter(ab)))